### ISSUE TITLE
Test failure: utest_ROI_analysis_T1_T2.py

### ISSUE THREAD

**Issue by mathieuboudreau** [imr-framework/virtual-scanner#31] opened 2019-08-20 13:03 UTC
FYI, I ran [this unit test](https://github.com/imr-framework/virtual-scanner/blob/master/virtualscanner/server/ana/utest_ROI_analysis_T1_T2.py) today and it failed. Here is the output,

<details>

```
(vs) mathieuboudreau@brassens:~/neuropoly/joss/virtual-scanner-2$ pythonw virtualscanner/server/ana/utest_ROI_analysis_T1_T2.py
virtualscanner/server/ana/utest_ROI_analysis_T1_T2.py:18: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  generated_ROI = imread(COMS_MAP_PATH / roi_filename)
/Users/mathieuboudreau/anaconda3/envs/vs/lib/python3.6/site-packages/scipy/misc/pilutil.py:165: DeprecationWarning: `fromimage` is deprecated!
`fromimage` is deprecated in SciPy 1.0.0. and will be removed in 1.2.0.
Use ``np.asarray(im)`` instead.
  return fromimage(im, flatten=flatten, mode=mode)
virtualscanner/server/ana/utest_ROI_analysis_T1_T2.py:19: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  utest_ROI = imread(SERVER_T1_MAP_PATH / 'utest_T1_map_with_ROI.png')
Fvirtualscanner/server/ana/utest_ROI_analysis_T1_T2.py:29: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  generated_ROI = imread(COMS_MAP_PATH / roi_filename)
virtualscanner/server/ana/utest_ROI_analysis_T1_T2.py:30: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  utest_ROI = imread(SERVER_T2_MAP_PATH / 'utest_T2_map_with_ROI.png')
F
======================================================================
FAIL: test_T1_ROI_analysis (__main__.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "virtualscanner/server/ana/utest_ROI_analysis_T1_T2.py", line 21, in test_T1_ROI_analysis
    np.testing.assert_allclose(generated_ROI, utest_ROI)
  File "/Users/mathieuboudreau/anaconda3/envs/vs/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 1493, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/Users/mathieuboudreau/anaconda3/envs/vs/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 819, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatch: 0.075%
Max absolute difference: 255
Max relative difference: nan
 x: array([[[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],...
 y: array([[[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],...

======================================================================
FAIL: test_T2_ROI_analysis (__main__.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "virtualscanner/server/ana/utest_ROI_analysis_T1_T2.py", line 32, in test_T2_ROI_analysis
    np.testing.assert_allclose(generated_ROI, utest_ROI)
  File "/Users/mathieuboudreau/anaconda3/envs/vs/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 1493, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/Users/mathieuboudreau/anaconda3/envs/vs/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 819, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatch: 0.235%
Max absolute difference: 255
Max relative difference: nan
 x: array([[[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],...
 y: array([[[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],...

----------------------------------------------------------------------
Ran 2 tests in 15.956s

FAILED (failures=2)

```

</details>

As a side note, it might be a good idea for your group to setup [continuous integration testing](https://crossbrowsertesting.com/blog/continuous-integration/continuous-integration-testing-delivery/), using some kind of free service like [Travis-CI](https://travis-ci.org). This way every time you push commits it will run all your tests automatically, and you'll be alerted when your test fails.

**Comment by qianenlin** [comment] 2019-08-23 20:58
The failure is caused by Mac/Windows inconsistencies. Fixed in bdcc5850b0f17a7c59d101b03da378007e13bd61.

**Closed by qianenlin** 2019-08-23 20:58 UTC
Labels: bug, review comment
