### ISSUE TITLE
Tx path problems

### ISSUE THREAD

**Issue by tonggehua** [imr-framework/virtual-scanner#14] opened 2019-07-15 16:58 UTC
When I select one of the two seq files in the "server\rf\tx\SAR_calc\assets" folder and hit calculate SAR, it gives the following error:

![image](https://user-images.githubusercontent.com/31249056/61233990-f2175f00-a6ff-11e9-81bf-4e41c399bf1c.png)

**Comment by sairamgeethanath** [comment] 2019-07-15 18:04
Not able to reproduce error on my system - Mac Book, also no image is generated when the sequence does not have at least 10 seconds of acquisition, the table reports NA

**Comment by sravan953** [comment] 2019-07-15 18:06
@sairamgeethanath A placeholder image for sequences < 10s might be a better idea.

**Comment by sairamgeethanath** [comment] 2019-07-15 18:10
@sravan953 I can add a default image but that would be an error message.

**Comment by sairamgeethanath** [comment] 2019-07-17 20:05
Fixed with commit imsg@818e65

**Closed by sairamgeethanath** 2019-07-17 20:05 UTC
Labels: bug
